### ISSUE TITLE
CakePHP 2.x

### ISSUE THREAD

**Issue by josephzidell** [fogcitymarathoner/CakePHP-PayPay-Adaptive-Payments#1]
This repository looks wonderful and is exactly what I'm looking for. Is it compatible with CakePHP 2.x?

**Comment by fogcitymarathoner** [comment]
huh?
It's yours!

**Comment by josephzidell** [comment]
What do you mean "it's yours"? The repository was uploaded in 2010, long before CakePHP 2.0 came out.

**Comment by fogcitymarathoner** [comment]
I'm just spooked because you are anonymous.
The code was written for 1.3.  If you needed to use it for 2.0 you would have to get the latest PayPal API, change the file name and rename the classes per 2.0 conventions.
Regards,
Marc
ebsiteswithclass [notifications@github.com]
Sent: Thursday, October 11, 2012 10:25 AM
To: fogcitymarathoner/CakePHP-PayPay-Adaptive-Payments
Cc: fogcitymarathoner
Subject: Re: [CakePHP-PayPay-Adaptive-Payments] CakePHP 2.x (#1)

What do you mean "it's yours"? The repository was uploaded in 2010, long before CakePHP 2.0 came out.

**Comment by josephzidell** [comment]
Besides the CakePHP 2.0 file naming conventions, there are other internal changes as well. Besides, I assume (based on prior PayPal API experience, but without absolute verification), that the API specification changed somewhat in the last 2 years.
